---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create Directory"
  file:
    path: ~/Udapeople
    state: directory

- name: "Extract Arifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/Udapeople

- name: "Start Application"
  shell:
    cd ~/Udapeople
    pm2 stop default
    pm2 start npm -- start